### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by davetapley** [rustyspoke/rustyspoke.github.io#6]
If you [reload without cache](https://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome#) (which forces the browser to re-download everything) then you'll see that it takes a long time for the background images to load.

This is because they're so big.
We should optimize them so they're only as big as needed.

**Comment by FrankieMarie** [comment]
I used something called "adaptive images" which automatically optimizes the images based on the screen its being viewed (supposedly) ... did it work? http://adaptive-images.com/

**Comment by davetapley** [comment]
D'oh, unfortunately that won't work because we're host it on GitHub Pages.

The problem is that the `.htacccess` fiel won't work, per [the docs](https://help.github.com/articles/redirects-on-github-pages/):

> For the security of our users, GitHub Pages does not support customer server configuration files such as `.htaccess`

**Comment by davetapley** [comment]
The good news is that this gives you a chance to use a neat feature of git called `git revert`.
There's more info [here](https://github.com/blog/2019-how-to-undo-almost-anything-with-git), but the quick version is:

If you do:

```
$ git revert 68f430c6b06aa293c93fba8d3ff042478ccd5331
```

Then `git` will generate a new commit, which undoes everything in that commit.
The that long number is called the SHA of a commit, it [uniquely identifies it](https://stackoverflow.com/questions/10434326/hash-collision-in-git/23253149#) from _every other commit in the world_. I found it by going [here](https://github.com/rustyspoke/rustyspoke.github.io/commits/master), if you click on a commit you'll go to a page [like this](https://github.com/rustyspoke/rustyspoke.github.io/commit/68f430c6b06aa293c93fba8d3ff042478ccd5331) where you can see the SHA of the commit and what changed in it.

***

After that, I'd probably just load the images in Photoshop (or whatever) and resize them down a bit, until they're say, max 960px wide (I just made that number up, but it seems ballpark average browser width).

**Comment by davetapley** [comment]
I did this revert ⬆️ and ran some image optimization, not great, but it'll do.

**Comment by FrankieMarie** [comment]
ahh thank you! I'm sorry i didn't get to it sooner!
